### ISSUE TITLE
UnhandledPromiseRejectionWarning: RangeError: Invalid typed array length: -1

### ISSUE THREAD

**Issue by chronoDave** [chronoDave/Doombox#47]
```
 (node:10428) UnhandledPromiseRejectionWarning: RangeError: Invalid typed array length: -1
    at new Uint8Array (<anonymous>)
    at decodeFrame (D:\Assets\Works\Projects\[ARC-016] Doombox\Doombox\packages\doombox-electron\src\lib\parser\decode.js:78:7)
    at D:\Assets\Works\Projects\[ARC-016] Doombox\Doombox\packages\doombox-electron\src\lib\parser\index.js:41:21
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
(node:10428) UnhandledPromiseRejectionWarning: RangeError: Invalid typed array length: -1
    at new Uint8Array (<anonymous>)
    at decodeFrame (D:\Assets\Works\Projects\[ARC-016] Doombox\Doombox\packages\doombox-electron\src\lib\parser\decode.js:78:7)
    at D:\Assets\Works\Projects\[ARC-016] Doombox\Doombox\packages\doombox-electron\src\lib\parser\index.js:41:21
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
(node:10428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chronoDave** [comment]
Related to #12
